# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

resources:
  repositories:
    - repository: templates
      type: github
      name: 'DevTeamHub/DevTeam.DevOps.Azure'
      endpoint: DevTeamHub
      ref: refs/tags/v1.0.2

variables:
  - group: Global

pool:
  vmImage: 'ubuntu-latest'

steps:
 
- template: build-net-project.yml@templates
  parameters:
    netSdkVersions: [$(PreviousVersion), $(CurrentVersion)]
    solution: $(Solution) 
    configuration: $(Configuration)

- template: publish-nuget-packages.yml@templates
  parameters:
    key: $(NugetKey) 
    configuration: $(Configuration)
