# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- deploy

resources:
  repositories:
    - repository: templates
      type: github
      name: 'DevTeamHub/DevTeam.DevOps.Azure'
      endpoint: DevTeamHub
      ref: refs/tags/v1.0.1

variables:
  - group: Global

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Set .Net Core SDK'
  inputs:
    version: '6.x'
    includePreviewVersions: true
  
- template: build-net-project.yml@templates
  parameters:
    netSdkVersion: $(NetSdkVersion)
    solution: $(Solution) 
    configuration: $(Configuration)

- task: DotNetCoreCLI@2
  displayName: 'Create Packages'
  inputs:
    command: pack
    arguments: '--configuration $(Configuration)'
