# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- deploy

resources:
  repositories:
    - repository: templates
      type: github
      name: 'DevTeamHub/DevTeam.DevOps.Azure'
      endpoint: DevTeamHub
      ref: refs/tags/v1.0.2

variables:
  - group: Global

pool:
  vmImage: 'ubuntu-latest'

steps:
 
- template: build-net-project.yml@templates
  parameters:
    netSdkVersions: [$(PreviousVersion), $(CurrentVersion)]
    solution: $(Solution) 
    configuration: $(Configuration)

- task: DotNetCoreCLI@2
  displayName: 'Create Packages'
  inputs:
    command: pack
    arguments: '--configuration $(Configuration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifacts'
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)
    artifactType: 'pipeline'
    artifactName: 'Packages'

- task: DotNetCoreCLI@2
  displayName: 'Upload to NuGet'
  inputs:
    command: 'nuget push'
    arguments: '$(Build.ArtifactStagingDirectory)/*.nupkg --api-key $(NugetKey)'
